### ISSUE TITLE
What is wrong ? leaflet.js error

### ISSUE THREAD

**Issue by FO-beep** [AndreaGT91/Park-Planner#8]
We're using leaflet.js to display a map. It throws out this message in the console:

** leaflet.js:5 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952 **

Do we need to be concerned about this? Is there a way to fix whatever the problem is?
chromestatus.comchromestatus.com

Passive event listeners - Chrome Platform Status

Expose "passive" boolean in the EventListenerOptions dictionary. Implement the behaviour with respect to dispatching passive EventListeners so that calling preventDefault inside executing the passive registered callback only generates a warning to the console. Can be used to dramatically improve scrolling performance.

**Comment by AndreaGT91** [comment]
Was able to correct by adding this line to the bottom of index.html:
<script type="text/javascript" src="https://unpkg.com/default-passive-events"></script>
